version: '3'
#
# services:
#   mongo:
#     image: mongo:6.0
#     restart: always
#     ports:
#       - 27018:27017
#     environment:
#       MONGODB_DATABASE: db
#   test-mongo:
#     image: mongo:6.0
#     restart: always
#     ports:
#       - 27019:27017
#     environment:
#       MONGODB_DATABASE: test-db

services:
  mongodb-primary:
    image: ${MONGODB_IMAGE_NAME}:${MONGODB_VERSION}
    restart: always
    expose:
      - ${MONGODB_PORT_NUMBER}
    ports:
      - ${MONGODB_PRIMARY_PORTS}
    environment:
      - MONGODB_ENABLE_IPV6=${MONGODB_ENABLE_IPV6}
      - MONGODB_ROOT_USER=${MONGODB_ROOT_USER}
      - MONGODB_ROOT_PASSWORD=${MONGODB_ROOT_PASSWORD}
      - MONGODB_REPLICA_SET_NAME=${MONGODB_REPLICA_SET_NAME}
      - MONGODB_REPLICA_SET_KEY=${MONGODB_REPLICA_SET_KEY}
      - MONGODB_REPLICA_SET_MODE=${MONGODB_PRIMARY_REPLICA_SET_MODE}
      - MONGODB_ADVERTISED_HOSTNAME=${MONGODB_PRIMARY_ADVERTISED_HOSTNAME}
    volumes:
      - ${MONGODB_PRIMARY_VOLUMES}

  mongodb-secondary:
    image: ${MONGODB_IMAGE_NAME}:${MONGODB_VERSION}
    restart: always
    depends_on:
      - mongodb-primary
    expose:
      - ${MONGODB_PORT_NUMBER}
    ports:
      - ${MONGODB_SECONDARY_PORTS}
    environment:
      - MONGODB_ENABLE_IPV6=${MONGODB_ENABLE_IPV6}
      - MONGODB_INITIAL_PRIMARY_HOST=${MONGODB_PRIMARY_ADVERTISED_HOSTNAME}
      - MONGODB_INITIAL_PRIMARY_PORT_NUMBER=${MONGODB_PRIMARY_PORTS}
      - MONGODB_INITIAL_PRIMARY_ROOT_PASSWORD=${MONGODB_ROOT_PASSWORD}
      - MONGODB_REPLICA_SET_NAME=${MONGODB_REPLICA_SET_NAME}
      - MONGODB_REPLICA_SET_KEY=${MONGODB_REPLICA_SET_KEY}
      - MONGODB_REPLICA_SET_MODE=${MONGODB_SECONDARY_REPLICA_SET_MODE}
      - MONGODB_ADVERTISED_HOSTNAME=${MONGODB_SECONDARY_ADVERTISED_HOSTNAME}

  mongodb-arbiter:
    image: ${MONGODB_IMAGE_NAME}:${MONGODB_VERSION}
    restart: always
    depends_on:
      - mongodb-primary
    expose:
      - ${MONGODB_PORT_NUMBER}
    ports:
      - ${MONGODB_ARBITER_PORTS}
    environment:
      - MONGODB_ENABLE_IPV6=${MONGODB_ENABLE_IPV6}
      - MONGODB_INITIAL_PRIMARY_HOST=${MONGODB_PRIMARY_ADVERTISED_HOSTNAME}
      - MONGODB_INITIAL_PRIMARY_PORT_NUMBER=${MONGODB_PRIMARY_PORTS}
      - MONGODB_INITIAL_PRIMARY_ROOT_PASSWORD=${MONGODB_ROOT_PASSWORD}
      - MONGODB_REPLICA_SET_NAME=${MONGODB_REPLICA_SET_NAME}
      - MONGODB_REPLICA_SET_KEY=${MONGODB_REPLICA_SET_KEY}
      - MONGODB_REPLICA_SET_MODE=${MONGODB_ARBITER_REPLICA_SET_MODE}
      - MONGODB_ADVERTISED_HOSTNAME=${MONGODB_ARBITER_ADVERTISED_HOSTNAME}
