# version: '3'
#
# services:
#   mongo:
#     image: mongo:5.0
#     restart: always
#     ports:
#       - 27018:27017
#     environment:
#       MONGODB_DATABASE: db
#   test-mongo:
#     image: mongo:5.0
#     restart: always
#     ports:
#       - 27019:27017
#     environment:
#       MONGODB_DATABASE: test-db

version: '2'

services:
  mongodb-primary:
    image: bitnami/mongodb:5.0
    restart: always
    ports:
      - 27017:27017
    environment:
      - MONGODB_ADVERTISED_HOSTNAME=mongodb-primary
      - MONGODB_REPLICA_SET_MODE=primary
      - MONGODB_ROOT_PASSWORD=mongodb
      - MONGODB_REPLICA_SET_KEY=replicasetkey
    volumes:
      - ~/bitnami/mongodb:/bitnami/mongodb

  mongodb-secondary:
    image: bitnami/mongodb:5.0
    restart: always
    depends_on:
      - mongodb-primary
    ports:
      - 27018:27017
    environment:
      - MONGODB_ADVERTISED_HOSTNAME=mongodb-secondary
      - MONGODB_REPLICA_SET_MODE=secondary
      - MONGODB_INITIAL_PRIMARY_HOST=mongodb-primary
      - MONGODB_INITIAL_PRIMARY_ROOT_PASSWORD=mongodb
      - MONGODB_REPLICA_SET_KEY=replicasetkey

  mongodb-arbiter:
    image: bitnami/mongodb:5.0
    restart: always
    depends_on:
      - mongodb-primary
    ports:
      - 27019:27017
    environment:
      - MONGODB_ADVERTISED_HOSTNAME=mongodb-arbiter
      - MONGODB_REPLICA_SET_MODE=arbiter
      - MONGODB_INITIAL_PRIMARY_HOST=mongodb-primary
      - MONGODB_INITIAL_PRIMARY_ROOT_PASSWORD=mongodb
      - MONGODB_REPLICA_SET_KEY=replicasetkey

volumes:
  mongodb_master_data:
    driver: local
