version: '3'

services:
  db:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGODB_DATABASE: db
  test-db:
    image: mongo
    restart: always
    ports:
      - 27018:27017
    environment:
      MONGODB_DATABASE: test-db
